# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('cc', models.IntegerField(default=49, help_text='Country code without +')),
                ('phone', models.IntegerField(help_text='Full phone number with country code but without +', primary_key=True, serialize=False)),
                ('mcc', models.IntegerField(choices=[(26203, 'O2'), (26201, 'Telekom'), (26202, 'Vodafone')], help_text='The mobile phone provider you are using.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Time when account was added.')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField(help_text='Phone number of WhatsApp account owner')),
                ('target', models.IntegerField(help_text='Full phone number of recepiant with country code but without +')),
                ('body', models.CharField(help_text='Message text', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time when message has been sent.')),
                ('status', models.CharField(choices=[('U', 'Unsend'), ('S', 'Sent'), ('A', 'Acknowledged')], default='U', max_length=1)),
            ],
        ),
    ]
