# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20170704_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='label',
            field=models.CharField(default='Sven Buschbeck', help_text='A name for this account to help identify the owner.', max_length=200),
            preserve_default=False,
        ),
    ]
