# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_account_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='api_password',
            field=models.CharField(default='NPpELYnv4y50CJDnhfKxcZZwb38=', help_text='The account password required to use the WhatsApp service. Automatically generated when creating and registering a new account.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='sms_code',
            field=models.CharField(default='xxx-xxx', help_text='The code received via SMS during registration xxx-xxx.', max_length=7),
            preserve_default=False,
        ),
    ]
