# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20170705_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cc',
            field=models.CharField(default=49, help_text='Country code without +', max_length=3),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(help_text='Full phone number with country code but without +', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='origin',
            field=models.CharField(help_text='Phone number of WhatsApp account owner', max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='target',
            field=models.CharField(help_text='Group ID or full phone number of recepient with country code but without +', max_length=50),
        ),
    ]
